server:
   port: 8085
spring:
  application:
    name: system-manager
  jackson:
    default-property-inclusion: non_empty
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp

  datasource:
    name: channel_system
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.6:3306/channel_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root
    initialize: true
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 5
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 10
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  type-aliases-package: com.longer.dao.model

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql




